-- --------------------------------------------------------
-- 服务器版本:                        PostgreSQL 16.4 (Debian 16.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS "User" (
	"id" BIGSERIAL PRIMARY KEY NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"nickname" VARCHAR(255) NULL DEFAULT NULL,
	"age" SMALLINT NULL DEFAULT NULL,
	"email" VARCHAR(255) NULL DEFAULT NULL,
	"phone" VARCHAR(255) NULL DEFAULT NULL,
	"password" VARCHAR(255) NULL DEFAULT NULL,
	"gender" BOOLEAN NULL DEFAULT NULL,
	"rank" INTEGER NULL DEFAULT NULL,
	"avatar" VARCHAR(1023) NULL DEFAULT NULL,
	"nationality" VARCHAR(32) NULL DEFAULT NULL,
	"create_time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"update_time" TIMESTAMPTZ NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "FriendVex" (
	"id" BIGSERIAL PRIMARY KEY NOT NULL,
	"user_id" BIGINT NOT NULL,
	"first_in" BIGINT NULL DEFAULT NULL,
	"first_out" BIGINT NULL DEFAULT NULL,
	"status" INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "FriendEdge" (
	"id" BIGSERIAL PRIMARY KEY NOT NULL,
	"headvex" BIGINT NULL DEFAULT NULL,
	"tailvex" BIGINT NULL DEFAULT NULL,
	"headlink" BIGINT NULL DEFAULT NULL,
	"status" SMALLINT DEFAULT 0
);
CREATE TABLE iF NOT EXISTS "Kifu" (
	"id" BIGSERIAL PRIMARY KEY NOT NULL,
	"player_1" BIGINT NULL DEFAULT NULL,
	"player_2" BIGINT NULL DEFAULT NULL,
	"mode" SMALLINT NULL DEFAULT NULL,
	"kifu_data" JSONB NULL DEFAULT NULL,
	"turn" BOOLEAN NULL DEFAULT NULL,
	"winner" SMALLINT NULL DEFAULT NULL,
	"status" SMALLINT NULL DEFAULT NULL,
	"sgf" TEXT NULL DEFAULT NULL,
	"create_time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"update_time" TIMESTAMPTZ NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "Analysis" (
	"id" BIGSERIAL PRIMARY KEY NOT NULL,
	"query_id" VARCHAR(255) NULL DEFAULT NULL,
	"is_running" BOOLEAN NOT NULL,
	"input_move" JSONB NULL DEFAULT NULL,
	"analysis_info" JSONB NULL DEFAULT NULL,
	"output_move" JSONB NULL DEFAULT NULL,
	"root_info" JSONB NULL DEFAULT NULL,
	"policy" JSONB NULL DEFAULT NULL,
	"hash" VARCHAR(127) NULL DEFAULT NULL,
	"turn_number" SMALLINT NULL DEFAULT NULL,
	"create_time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"update_time" TIMESTAMPTZ NULL DEFAULT NULL
);