"""empty message

Revision ID: 839b2c40f213
Revises: 
Create Date: 2024-03-09 12:47:12.428203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839b2c40f213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('_password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('go_hist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('play_datetime', sa.DateTime(), nullable=True),
    sa.Column('game_name', sa.String(length=64), nullable=False),
    sa.Column('game_data', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('go_hist')
    op.drop_table('users')
    # ### end Alembic commands ###
