"""empty message

Revision ID: e3d047cb6fea
Revises: bdc8d4c2120b
Create Date: 2024-03-06 20:49:19.006548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d047cb6fea'
down_revision = 'bdc8d4c2120b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('go_hist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('play_datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('go_hist', schema=None) as batch_op:
        batch_op.drop_column('play_datetime')
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
