"""empty message

Revision ID: f59c85574671
Revises: 4061ceb64d76
Create Date: 2024-03-04 23:39:21.452910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59c85574671'
down_revision = '4061ceb64d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('go_hist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_data', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('go_hist', schema=None) as batch_op:
        batch_op.drop_column('game_data')

    # ### end Alembic commands ###
